version: '3.7'
services:

  header:
    # Makefile fills PROJECT_NAME to current directory name.
    # add UID to allow multiple users run this in parallel
    container_name: ${PROJECT_NAME}:header-${HOST_USER}
    hostname: ${PROJECT_NAME}
    # These variables are passed into the container.
    environment:
      - PWD=${PWD}
      - UMBREL=${UMBREL}
      - THIS_FILE=${THIS_FILE}
      - TIME=${TIME}
      - HOST_USER=${HOST_USER}
      - HOST_UID=${HOST_UID}
      - SERVICE_TARGET=${SERVICE_TARGET}
      - ALPINE_VERSION=${ALPINE_VERSION}
      - WHISPER_VERSION=${WHISPER_VERSION}
      - CARBON_VERSION=${CARBON_VERSION}
      - GRAPHITE_VERSION=${GRAPHITE_VERSION}
      - STATSD_VERSION=${STATSD_VERSION}
      - GRAFANA_VERSION=${GRAFANA_VERSION}
      - DJANGO_VERSION=${DJANGO_VERSION}
      - PROJECT_NAME=${PROJECT_NAME}
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - GIT_SERVER=${GIT_SERVER}
      - GIT_PROFILE=${GIT_PROFILE}
      - GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}
      - GIT_REPO_NAME=${GIT_REPO_NAME}
      - GIT_REPO_PATH=${GIT_REPO_PATH}
      - DOCKERFILE=${DOCKERFILE}
      - DOCKERFILE_PATH=${DOCKERFILE_PATH}
      - BITCOIN_CONF=${BITCOIN_CONF}
      - BITCOIN_DATA_DIR=${BITCOIN_DATA_DIR}
      - STATOSHI_DATA_DIR=${STATOSHI_DATA_DIR}
      - NOCACHE=${NOCACHE}
      - VERBOSE=${VERBOSE}
      - PUBLIC_PORT=${PUBLIC_PORT}
      - NODE_PORT=${NODE_PORT}
      - PASSWORD=${PASSWORD}
      - CMD_ARGUMENTS=${CMD_ARGUMENTS}
    # Run with user priviliges by default.
    user: root #${HOST_USER:-nodummy}
    image: ${PROJECT_NAME}:header-${HOST_USER}
    restart: unless-stopped
    build:
      context: .
      # This is the name of the last layer in shell
      target: header
      dockerfile: docker/header
      # These variables are passed to Dockerfile.
      args:
        - PWD=${PWD}
        - UMBREL=${UMBREL}
        - THIS_FILE=${THIS_FILE}
        - TIME=${TIME}
        - HOST_USER=${HOST_USER}
        - HOST_UID=${HOST_UID}
        - SERVICE_TARGET=${SERVICE_TARGET}
        - ALPINE_VERSION=${ALPINE_VERSION}
        - WHISPER_VERSION=${WHISPER_VERSION}
        - CARBON_VERSION=${CARBON_VERSION}
        - GRAPHITE_VERSION=${GRAPHITE_VERSION}
        - STATSD_VERSION=${STATSD_VERSION}
        - GRAFANA_VERSION=${GRAFANA_VERSION}
        - DJANGO_VERSION=${DJANGO_VERSION}
        - PROJECT_NAME=${PROJECT_NAME}
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
        - GIT_SERVER=${GIT_SERVER}
        - GIT_PROFILE=${GIT_PROFILE}
        - GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}
        - GIT_REPO_NAME=${GIT_REPO_NAME}
        - GIT_REPO_PATH=${GIT_REPO_PATH}
        - DOCKERFILE=${DOCKERFILE}
        - DOCKERFILE_PATH=${DOCKERFILE_PATH}
        - BITCOIN_CONF=${BITCOIN_CONF}
        - BITCOIN_DATA_DIR=${BITCOIN_DATA_DIR}
        - STATOSHI_DATA_DIR=${STATOSHI_DATA_DIR}
        - NOCACHE=${NOCACHE}
        - VERBOSE=${VERBOSE}
        - PUBLIC_PORT=${PUBLIC_PORT}
        - PASSWORD=${PASSWORD}
        - CMD_ARGUMENTS=${CMD_ARGUMENTS}
    # Run container as a service. Replace with something useful.
    #command: ["tail", "-f", "/dev/null"]
    # Copy current (git-) project into container.
    volumes:
      - ${HOME:-.}:/home/${HOST_USER}:consistent
      - ${HOME:-.}/.bitcoin:/home/${HOST_USER}/.bitcoin:consistent
      - ${HOME:-.}/.statoshi:/home/${HOST_USER}/.statoshi:consistent

  statoshi:
    # Makefile fills PROJECT_NAME to current directory name.
    # add UID to allow multiple users run this in parallel
    container_name: ${PROJECT_NAME}_${HOST_UID:-4000}
    hostname: ${PROJECT_NAME}
    # These variables are passed into the container.
    environment:
      - PWD=${PWD}
      - UMBREL=${UMBREL}
      - THIS_FILE=${THIS_FILE}
      - TIME=${TIME}
      - HOST_USER=${HOST_USER}
      - HOST_UID=${HOST_UID}
      - SERVICE_TARGET=${SERVICE_TARGET}
      - ALPINE_VERSION=${ALPINE_VERSION}
      - WHISPER_VERSION=${WHISPER_VERSION}
      - CARBON_VERSION=${CARBON_VERSION}
      - GRAPHITE_VERSION=${GRAPHITE_VERSION}
      - STATSD_VERSION=${STATSD_VERSION}
      - GRAFANA_VERSION=${GRAFANA_VERSION}
      - DJANGO_VERSION=${DJANGO_VERSION}
      - PROJECT_NAME=${PROJECT_NAME}
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - GIT_SERVER=${GIT_SERVER}
      - GIT_PROFILE=${GIT_PROFILE}
      - GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}
      - GIT_REPO_NAME=${GIT_REPO_NAME}
      - GIT_REPO_PATH=${GIT_REPO_PATH}
      - DOCKERFILE=${DOCKERFILE}
      - DOCKERFILE_PATH=${DOCKERFILE_PATH}
      - BITCOIN_CONF=${BITCOIN_CONF}
      - BITCOIN_DATA_DIR=${BITCOIN_DATA_DIR}
      - STATOSHI_DATA_DIR=${STATOSHI_DATA_DIR}
      - NOCACHE=${NOCACHE}
      - VERBOSE=${VERBOSE}
      - PUBLIC_PORT=${PUBLIC_PORT}
      - NODE_PORT=${NODE_PORT}
      - PASSWORD=${PASSWORD}
      - CMD_ARGUMENTS=${CMD_ARGUMENTS}
    # Run with user priviliges by default.
    user: ${HOST_USER:-nodummy}
    image: ${PROJECT_NAME}:${HOST_USER:-nodummy}
    restart: unless-stopped
    build:
      context: .
      # This is the name of the last layer in stats.bitcoincore.dev
      target: statoshi
      dockerfile: ${PROJECT_NAME}
      # These variables are passed to Dockerfile.
      args:
        - PWD=${PWD}
        - UMBREL=${UMBREL}
        - THIS_FILE=${THIS_FILE}
        - TIME=${TIME}
        - HOST_USER=${HOST_USER}
        - HOST_UID=${HOST_UID}
        - SERVICE_TARGET=${SERVICE_TARGET}
        - ALPINE_VERSION=${ALPINE_VERSION}
        - WHISPER_VERSION=${WHISPER_VERSION}
        - CARBON_VERSION=${CARBON_VERSION}
        - GRAPHITE_VERSION=${GRAPHITE_VERSION}
        - STATSD_VERSION=${STATSD_VERSION}
        - GRAFANA_VERSION=${GRAFANA_VERSION}
        - DJANGO_VERSION=${DJANGO_VERSION}
        - PROJECT_NAME=${PROJECT_NAME}
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
        - GIT_SERVER=${GIT_SERVER}
        - GIT_PROFILE=${GIT_PROFILE}
        - GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}
        - GIT_REPO_NAME=${GIT_REPO_NAME}
        - GIT_REPO_PATH=${GIT_REPO_PATH}
        - DOCKERFILE=${DOCKERFILE}
        - DOCKERFILE_PATH=${DOCKERFILE_PATH}
        - BITCOIN_CONF=${BITCOIN_CONF}
        - BITCOIN_DATA_DIR=${BITCOIN_DATA_DIR}
        - STATOSHI_DATA_DIR=${STATOSHI_DATA_DIR}
        - NOCACHE=${NOCACHE}
        - VERBOSE=${VERBOSE}
        - PUBLIC_PORT=${PUBLIC_PORT}
        - NODE_PORT=${NODE_PORT}
        - PASSWORD=${PASSWORD}
        - CMD_ARGUMENTS=${CMD_ARGUMENTS}
    # Run container as a service. Replace with something useful.
    #command: ["tail", "-f", "/dev/null"]
    command:  ["/usr/local/bin/entrypoint"]
    # Expose current project folder to container.
    volumes:
      - ${HOME:-.}:/home/${HOST_USER}:consistent
      - ${HOME:-.}/.bitcoin:/home/${HOST_USER}/.bitcoin:consistent
      - ${HOME:-.}/.statoshi:/home/${HOST_USER}/.statoshi:consistent
    ports:
       #hostPORT:imagePORT
     - "8332:8332"
     - "${NODE_PORT}:8333"
     - "18333:18333"

