# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: |
         make init
         make run user=root

  ubuntu20:
    runs-on: ubuntu20
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: |
         make init
         make run user=root

  ubuntu18:
    runs-on: ubuntu18
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: |
         make init
         make run user=root

