# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ubuntu-latest-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: |
         make init
         make run user=root

  ubuntu20-docker:
    runs-on: ubuntu20
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: |
         make init
         make run user=root

  ubuntu18-docker:
    runs-on: ubuntu18
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: |
         make init
         make run user=root

  ubuntu-latest-build-on-host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: |
         make init
         sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
         make -C depends
         ./autogen.sh
         ./configure --disable-wallet --disable-tests --disable-bench --disable-docs
         
  ubuntu20-build-on-host:
    runs-on: ubuntu20
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: |
         make init
         sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
         make -C depends
         ./autogen.sh
         ./configure --disable-wallet --disable-tests --disable-bench --disable-docs
         
  ubuntu18-build-on-host:
    runs-on: ubuntu18
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: |
         make init
         sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
         make -C depends
         ./autogen.sh
         ./configure --disable-wallet --disable-tests --disable-bench --disable-docs
         
