# This is a basic workflow to help you get started with Actions

name: test-command.yml

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - '.github/workflows/test-command.yml'
      - './conf'
      - './docker'
      - './GNUmakefile'
    schedule:
      - cron: "*/5 * * * *"

    branches:       #[ master ]
      - 'master'    # includes master
      - 'main'      # includes main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ubuntu-18-host:
    runs-on: [ubuntu-18.04, self-hosted]
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: statoshi-command
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && \
          brew install docker docker-compose make && \
          git clone https://github.com/bitcoincore-dev/statoshi.host.git ~/statoshi.host && \
          cd ~/statoshi.host && make init run user=root port=80

  macos-10-host:
    runs-on: [macos-10.15, self-hosted]
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: statoshi-command
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && \
          brew install docker docker-compose make && \
          git clone https://github.com/bitcoincore-dev/statoshi.host.git ~/statoshi.host && \
          cd ~/statoshi.host && make init run user=root port=80

