# This is a basic workflow to help you get started with Actions

name: u-l-make-docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

## Docker Configs
  u-l-make-docs:
    runs-on: ubuntu-latest
    steps:
      ## REF: https://githubmemory.com/repo/Gisleburt/cancel-workflow-action
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@master
        with:
        # Fetch the last 2 commits instead of just 1.
        # (Fetching just 1 commit would overwrite the whole history)
          fetch-depth: 10
        # Other steps in your workflow to trigger a changed file
      - name: make init docs 
        id: last-commit-message
        run: |
          git reset --soft HEAD~1
          make init docs nocache=true verbose=true cmd='./conf/usr/local/bin/stats'
          echo "::set-output name=msg::$(git log -1 --pretty=%s)"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true

